spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: {username}
    url: jdbc:mysql://{address}:{port}/{DB_name}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: {password}

  jpa:
    open-in-view: 'true'
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    show-sql: 'true'

  jwt:
    secretKey: bow-wow-care

cloud:
  aws:
    s3:
      bucket: {bucket_name}
    credentials:
      access-key: {access-key}
      secret-key: {secret-key}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          com.amazonaws.util.EC2MetadataUtils: ERROR